# Generated by Django 6.1 on 2026-08-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='qr_codes/'),
        ),
    ]
