# Generated by Django 6.1 on 2026-09-05 15:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'attendance',
            '0003_alter_student_qr_code'
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [

        # GPS Latitude
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(
                blank=True,
                null=True
            ),
        ),

        # Location verification
        migrations.AddField(
            model_name='attendance',
            name='location_verified',
            field=models.BooleanField(
                default=False
            ),
        ),

        # GPS Longitude
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(
                blank=True,
                null=True
            ),
        ),

        # Dynamic QR Session ID
        migrations.AddField(
            model_name='attendance',
            name='session_id',
            field=models.CharField(
                db_index=True,
                default='legacy',
                max_length=100
            ),
        ),

        # Student Login User
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='student_profile',
                to=settings.AUTH_USER_MODEL
            ),
        ),

        # Attendance Date
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(
                default=django.utils.timezone.localdate
            ),
        ),

        # Student relationship
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attendances',
                to='attendance.student'
            ),
        ),

    ]